---
name: "Jav"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
imageUrl: "https://raw.githubusercontent.com/chenqiaoanying/jellyfin-plugin-jav/master/Jellyfin.Plugin.Jav/logo.png"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "A jellyfin plugin used to fetch movie and actor info"
description: >
  A jellyfin plugin used to fetch movie and actor info.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Jav.dll"
changelog: >
  fetch movie and actor info by jav-service
