name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Build Jellyfin Plugin
        uses: oddstr13/jellyfin-plugin-repository-manager@v0.5.0
        id: jprm
        with:
          dotnet-target: "net6.0"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: ${{ steps.jprm.outputs.artifact }}

  upload:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build-artifact

      - name: Prepare GH Release Assets
        run: |-
          for file in ./*; do
            md5sum ${file#./} >> ${file%.*}.md5
            sha256sum ${file#./} >> ${file%.*}.sha256
          done
          ls -l

      - name: Upload GH Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*

      - name: Checkout Plugin Manifest
        shell: bash
        run: |-
          git config --global user.name  'jav-bot'
          git config --global user.email 'jav-bot@users.noreply.github.com'
          git init
          git remote add origin https://x-access-token:${{ secrets.MANIFEST_REPOSITORY_TOKEN }}@github.com/chenqiaoanying/jellyfin-plugin-jav-manifest
          git fetch origin main
          git checkout -t origin/main

      - name: Create Plugin Manifest
        shell: bash
        run: |-
          URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${{ github.event.release.tag_name }}/$(basename $(ls ./*.zip))"
          echo $URL
          pip install jprm
          jprm --verbosity=debug repo add -U $URL . ./*.zip

      - name: Publish Plugin Manifest
        shell: bash
        run: |-
          git add manifest.json
          git commit -m "updated by github action"
          git push
